//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fault_Client_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaultTbl
    {
        public int FaultID { get; set; }
        public string FaultType { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string AssignedTo { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string Decription { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public string Status { get; set; }
    }
}
