//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fault_Client_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaultingTbl
    {
        public int FaultingID { get; set; }
        public Nullable<int> FaultID { get; set; }
        public string ImagePath { get; set; }
    }
}
