//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fault_Client_Dashboard.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SdDatabaseEntities : DbContext
    {
        public SdDatabaseEntities()
            : base("name=SdDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminTbl> AdminTbls { get; set; }
        public virtual DbSet<FaultingTbl> FaultingTbls { get; set; }
        public virtual DbSet<ClientTbl> ClientTbls { get; set; }
        public virtual DbSet<FaultTbl> FaultTbls { get; set; }
    }
}
